export const GET_COMMENT = "GET_COMMENT";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAILURE = "GET_COMMENT_FAILURE";
export const POST_COMMENT = "POST_COMMENT"
export const POST_COMMENT_SUCCESS="POST_COMMENT_SUCCESS"
export const POST_COMMENT_FAILURE="POST_COMMENT_FAILURE"
